/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventariobodega.forms;

import java.awt.BorderLayout;

/**
 *
 * @author OSCAR
 * 
 * Este programa Java define una interfaz gráfica de usuario (GUI) para una aplicación de inventario de bodega. 
 */
// ventana de aplicacion
public class paginaPrincipal extends javax.swing.JFrame {

    //constructor
    public paginaPrincipal() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        panelContenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        inventario = new javax.swing.JMenu();
        ingresarProducto = new javax.swing.JMenu();
        menuInsertar = new javax.swing.JMenu();
        nProducto = new javax.swing.JMenu();
        nCategoria = new javax.swing.JMenu();
        nMarca = new javax.swing.JMenu();
        nMedida = new javax.swing.JMenu();
        nProveedor = new javax.swing.JMenu();
        nUbicacion = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));
        panelContenido.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido usuario");
        panelContenido.add(jLabel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        inventario.setText("Inventario");
        inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventarioMouseClicked(evt);
            }
        });
        jMenuBar1.add(inventario);

        ingresarProducto.setText("ingresar producto");
        ingresarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarProductoMouseClicked(evt);
            }
        });
        jMenuBar1.add(ingresarProducto);

        menuInsertar.setText("insertar nuevo dato");

        nProducto.setText("Nuevo producto");
        nProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nProductoMouseClicked(evt);
            }
        });
        nProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nProductoActionPerformed(evt);
            }
        });
        menuInsertar.add(nProducto);

        nCategoria.setText("Nueva categoria");
        nCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nCategoriaMouseClicked(evt);
            }
        });
        menuInsertar.add(nCategoria);

        nMarca.setText("Nueva marca");
        nMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nMarcaMouseClicked(evt);
            }
        });
        menuInsertar.add(nMarca);

        nMedida.setText("Nueva medida");
        nMedida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nMedidaMouseClicked(evt);
            }
        });
        menuInsertar.add(nMedida);

        nProveedor.setText("Nuevo proveedor");
        nProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nProveedorMouseClicked(evt);
            }
        });
        menuInsertar.add(nProveedor);

        nUbicacion.setText("Nueva ubicacion ");
        nUbicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nUbicacionMouseClicked(evt);
            }
        });
        menuInsertar.add(nUbicacion);

        jMenuBar1.add(menuInsertar);

        jMenu2.setText("Manual de usuario");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nProductoActionPerformed
        
    }//GEN-LAST:event_nProductoActionPerformed

    //accion para traer jpanel de nuevo producto
    private void nProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nProductoMouseClicked
       panelContenido.removeAll();// elimina los componentes existentes del panelControl
        nuevoProducto panelProducto = new nuevoProducto();// crea una nueva instancia del panel
        panelContenido.add(panelProducto, BorderLayout.CENTER); //agrega un nuevo panel
        panelContenido.revalidate();// revalida para que los cambios se reflejen
        panelContenido.repaint();//redibuja el panelContenido para mostrar los cambios visuales
        // las mismas funciones se ejecutan para cada accion
    }//GEN-LAST:event_nProductoMouseClicked

    //accion para traer jpanel para ingresar una nueva categoria
    private void nCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nCategoriaMouseClicked
       
        panelContenido.removeAll();
        nuevaCategoria panelCategoria=new nuevaCategoria();
        panelContenido.add(panelCategoria,BorderLayout.CENTER);
        panelContenido.revalidate();
        panelContenido.repaint();
    }//GEN-LAST:event_nCategoriaMouseClicked

    //accion para traer jpanel de nueva marca
    private void nMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nMarcaMouseClicked
        
        panelContenido.removeAll();
        nuevaMarca panelMarca=new nuevaMarca();
        panelContenido.add(panelMarca,BorderLayout.CENTER);
        panelContenido.revalidate();
        panelContenido.repaint();
    }//GEN-LAST:event_nMarcaMouseClicked

    //accion para traer jpanel de nueva medida
    private void nMedidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nMedidaMouseClicked
        
        panelContenido.removeAll();
        nuevaMedida panelMedida=new nuevaMedida();
        panelContenido.add(panelMedida,BorderLayout.CENTER);
        panelContenido.revalidate();
        panelContenido.repaint();
    }//GEN-LAST:event_nMedidaMouseClicked

    //accion para traer jpanel de nueva ubicacion
    private void nUbicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nUbicacionMouseClicked

        panelContenido.removeAll();
        nuevaUbicacion panelUbicacion=new nuevaUbicacion();
        panelContenido.add(panelUbicacion,BorderLayout.CENTER);
        panelContenido.revalidate();
        panelContenido.repaint();
       
    }//GEN-LAST:event_nUbicacionMouseClicked

    //accion para traer jpanel de nuevo proveedor
    private void nProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nProveedorMouseClicked
       
        panelContenido.removeAll();
        nuevoProveedor panelProveedor=new nuevoProveedor();
        panelContenido.add(panelProveedor,BorderLayout.CENTER);
        panelContenido.revalidate();
        panelContenido.repaint();
    }//GEN-LAST:event_nProveedorMouseClicked

    //accion para traer jpanel de nuevo producto
    private void ingresarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarProductoMouseClicked
       
        panelContenido.removeAll();
        ingresarProducto panelIngresar= new ingresarProducto();
        panelContenido.add(panelIngresar,BorderLayout.CENTER);
        panelContenido.revalidate();
        panelContenido.repaint();
    }//GEN-LAST:event_ingresarProductoMouseClicked

    //accion para traer jpanel del inventario
    private void inventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventarioMouseClicked
      
        panelContenido.removeAll();
        inventario panelInventario=new inventario();
        panelContenido.add(panelInventario,BorderLayout.CENTER);
        panelContenido.revalidate();
        panelContenido.repaint();
    }//GEN-LAST:event_inventarioMouseClicked

    /**
     * @param args the command line arguments
     */
    //
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ingresarProducto;
    private javax.swing.JMenu inventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menuInsertar;
    private javax.swing.JMenu nCategoria;
    private javax.swing.JMenu nMarca;
    private javax.swing.JMenu nMedida;
    private javax.swing.JMenu nProducto;
    private javax.swing.JMenu nProveedor;
    private javax.swing.JMenu nUbicacion;
    private javax.swing.JPanel panelContenido;
    // End of variables declaration//GEN-END:variables
}
